spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:locahost}:5432/jobcrawler
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:changeme}
    #Execute data.sql upon initialization
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        metadata_builder_contributor: nl.ordina.jobcrawler.configuration.SqlFunctionsMetadataBuilderContributor

server.error.include-stacktrace: on_trace_param

##Uncomment below to see wellformed sql logging with binded parameters
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


